name = "xatosfera"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "crm"
database_id = "d8ee9d0c-ac4d-4f23-b1ff-8ac3d9a3d5a6"

[[r2_buckets]]
binding = "R2"
bucket_name = "crm"
